#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ScutLogin.Droid.Resource", IsApplication=true)]

namespace ScutLogin.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_perm_scan_wifi_white_24dp = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_refresh_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_wifi_lock_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int logo_about = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int about = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int autoLogin = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int errorText = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int loginButton = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int logoutButton = 2131099655;
			
			// aapt resource value: 0x7f060003
			public const int password = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int refresh = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int savePassword = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int statusText = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int userName = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int MainMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int about = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int refreshStatus = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int version = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
